# Generated by Django 4.1.2 on 2022-12-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='entity_time',
        ),
        migrations.AddField(
            model_name='botuser',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
